### PR TITLE
Update Todo.py

### PR DESCRIPTION
**Pull request by whatsinmyopsec**
I changed your theme and updated your imports

### CODE REVIEW

**Comment by adityamangal1** [comment]
Thanks for the contribution @whatsinmyopsec  Make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech

**Comment by LunarWatcher** [comment]
Joining an organization isn't a requirement for Hacktoberfest to count PRs.

**Comment by MattIPv4** [comment]
👋 Hey @adityamangal1 -- forcing advertising upon folks and making them join your Discord server before you accept their contribution doesn't seem like a very friendly thing to be doing? Someone has taken the time and effort to make a contribution to your project, don't use that to then growth-hack your server, refusing to acknowledge their work until they do so.

Sure, you can suggest that they join your Discord to collaborate further, but if a user has made a valuable contribution, you should be able to accept it without forcing them to join a Discord server if they don't want to...

Frankly, it seems that you're trying to abuse Hacktoberfest and this repo to bait people into making contributions in an attempt to boost your Discord, rather than to actually get open source contributions, which is not cool at all.

**Comment by Nitesh-thapliyal** [comment]
> 👋 Hey @adityamangal1 -- forcing advertising upon folks and making them join your Discord server before you accept their contribution doesn't seem like a very friendly thing to be doing? Someone has taken the time and effort to make a contribution to your project, don't use that to then growth-hack your server, refusing to acknowledge their work until they do so.
> 
> Sure, you can suggest that they join your Discord to collaborate further, but if a user has made a valuable contribution, you should be able to accept it without forcing them to join a Discord server if they don't want to...
> 
> Frankly, it seems that you're trying to abuse Hacktoberfest and this repo to bait people into making contributions in an attempt to boost your Discord, rather than to actually get open source contributions, which is not cool at all.

Sorry for the inconvenience caused, it is not compulsory to stay on the server, we are just making sure that every contribution is genuine as we are having sessions on the server regarding contributions to resolve any issues with contributions, issues, PR.

**Review by Nitesh-thapliyal — COMMENTED** [review]
Can you share the snapshot of the changes made, it will be helpfull.

**Pull request closed without merging**
